POST http://localhost:8080/todos/
Content-Type: application/json

{
  "title": "Hello World",
  "completed": "False",
  "order": 1
}

###
# Test your endpoints

GET http://localhost:8080/todos/
Accept: application/json

###
GET http://localhost:8080/todos/1
Accept: application/json

###
GET http://127.0.0.1:8080/tags/
Accept: application/json

###
GET http://127.0.0.1:8080/tags/1
Accept: application/json

###